### ISSUE TITLE
which of the svgs should i use?

### ISSUE THREAD

**Issue by owocki** [vinhbhn/gitcoin-avatar-builder-autumn-2021#1]
which of the svgs should i use?

**Comment by owocki** [comment]
robot 1 or robot 2

**Comment by vinhbhn** [comment]
@owocki I think you should use robot 1

**Comment by owocki** [comment]
ok that robot needs to have permuations of appendages/heads/eyes/whatever to go into the avatar builder. its just 1 avatar rn

**Comment by vinhbhn** [comment]
@owocki I have updated it. You can review it.
